module.exports = {
  "intro": "ECMAScript 6简介",
  "let": "let 和 const 命令",
  "destructuring": "变量的解构赋值",
  "string": "字符串的扩展",
  "stringmethods": "字符串的新增方法",
  "regex": "正则的扩展",
  "number": "数值的扩展",
  "function": "函数的扩展",
  "array": "数组的扩展",
  "object": "对象的扩展",
  "objectmethods": "对象的新增方法",
  "operator": "运算符的扩展",
  "symbol": "Symbol",
  "setmap": "Set 和 Map 数据结构",
  "proxy": "Proxy",
  "reflect": "Reflect",
  "promise": "Promise 对象",
  "iterator": "Iterator 和 for...of 循环",
  "generator": "Generator 函数的语法",
  "generatorasync": "Generator 函数的异步应用",
  "async": "async 函数",
  "class": "Class 的基本语法",
  "classextends": "Class 的继承",
  "module": "Module 的语法",
  "moduleloader": "Module 的加载实现",
  "style": "编程风格",
  "spec": "读懂规格",
  "asynciterator": "异步遍历器",
  "arraybuffer": "ArrayBuffer",
  "proposals": "最新提案",
  "reference": "参考链接",
  "decorator": "Decorator",
  "mixin": "Mixin",
  "simd": "Simd",
  "acknowledgment":"鸣谢",
  "fp":"函数式编程",
}