name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - main
    paths-ignore: # 下列文件的变更不触发部署
      - LICENSE
# 任务
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest #部署运行环境搭建
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0 #github代码拉取深度

      - name: Setup Node  🎬
        uses: actions/setup-node@main
        with
          node-version: 'lts/*'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Build 🔧
        run: |
          pnpm install
          pnpm run build
          ls -lrth

      - name: 📲 Push To GitHub Pages
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: dist
          github_token: ${{ secrets.DEPLOY_TOKEN }}
